Try to implement the grammar in fluent.mjs in tree-sitter
We wonder if there's a difference in the capabilities of the
parser logic in fluent.mjs and parsers.mjs to tree-sitter, or if
the parser compiler in tree-sitter is just over protective.

The current state fails on tree-sitter generate with:

Error: Unresolved conflict for symbol sequence:

'  …neBreak_repeat1  •  '

Possible interpretations:

'  …  (lineBreak  lineBreak_repeat1)  •  '
  2:  (lineBreak_repeat1  lineBreak_repeat1  •  lineBreak_repeat1)

Possible resolutions:

  1:  Specify a left or right associativity in `lineBreak`
  2:  Add a conflict for these rules: `lineBreak`